### ISSUE TITLE
Add volume attributes for supporting mounting several images at the same time

### ISSUE THREAD

**Issue by davidfestal** [davidfestal/csi-based-tool-provider#2]
We should introduce new CSI volume attributes to support mounting several images at the same time.
Something like:
```yaml
      - name: tools
        csi:
          driver: toolprovider.csi.katalogos.dev
          volumeAttributes:
            image.java: quay.io/dfestal/csi-tool-openjdk11u-jdk_x64_linux_hotspot_11.0.9.1_1:latest
            image.maven: quay.io/dfestal/csi-tool-maven-3.6.3:latest
``` 
In other words, when attributes are `image.` (with a prefix), there can be several images and each one would be mounted, in the Pod volume, at the subpath corresponding to the suffix that follows `image.`.

This issue is part of EPIC https://github.com/katalogos/csi-based-tool-provider/issues/1
